[package]
name = "rink-core"
version = "0.5.0"
authors = ["Tiffany Bennett <tiffany@stormbit.net>"]
description = "Unit conversion library behind rink"
homepage = "https://github.com/tiffany352/rink-rs"
repository = "https://github.com/tiffany352/rink-rs"
readme = "README.md"
license = "MPL-2.0"
keywords = ["unit", "math", "conversion"]
edition = "2018"

[features]
default = ["chrono-humanize", "gpl"]
gpl = []

[dependencies]
num = "0.3.0"
chrono = "0.2.25"
strsim = "0.5.1"
chrono-tz = "0.2.2"
chrono-humanize = { version = "0.0.6", optional = true }
xml-rs = { version = "0.3.4" }
json = { version = "0.10.2" }
serde = { version = "1", features = ["rc"] }
serde_derive = "1"
